calorieapp/new_way/calorie_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calories.urls')),
    path('users/', include('users.urls')),
    path('food/', include('food.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
]

calorieapp/new_way/calories/urls.py
from django.urls import path

from .views import CalProfile, CalProfilePageView, calprofile

app_name = 'calories'

urlpatterns = [

    path('',CalProfilePageView, name='home'),
    path('calprofile', CalProfile.as_view() , name='calprofile'),

]

calorieapp/new_way/food/urls.py
from django.urls import path

from .views import  AddFood, FoodPerDay 
from .views import select_food,update_food,delete_food

app_name = 'food'

urlpatterns = [

    
    path('select_food/', select_food, name='select_food'),
	path('add_food/', AddFood.as_view(), name='add_food'),
	path('update_food/<str:pk>/', update_food, name='update_food'),
	path('delete_food/<str:pk>/', delete_food, name='delete_food'),
    path('profile/', FoodPerDay , name='profile'),
    

]

calorieapp/new_way/food/models.py
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL


# Create your models here.

class Food(models.Model):

    name = models.CharField(max_length=200, null=False)
    quantity = models.PositiveIntegerField(null=False, default=0)
    calorie = models.FloatField(null=False, default=0)
    person_of = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

calorieapp/new_way/food/forms.py
from django import forms

from calories.models import FoodPerDay, Food


class SelectFoodForm(forms.ModelForm):
    class Meta:
        model = FoodPerDay
        fields = ('food_selected', 'quantity',)

    def __init__(self, user, *args, **kwargs):
        super(SelectFoodForm, self).__init__(*args, **kwargs)
        self.fields['food_selected'].queryset = Food.objects.filter(person_of=user)


class AddFoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ('name', 'quantity', 'calorie')

calorieapp/new_way/food/views.py
from audioop import add, reverse
import imp
from unicodedata import name
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from food.filters import FoodFilter
from calories.models import CalorieGoal, FoodPerDay, Food
from .forms import SelectFoodForm, AddFoodForm
from django.core.paginator import Paginator, EmptyPage
from django.views.generic import ListView
# Create your views here.


class AddFood(ListView):
    model = Food
    template_name = 'add_food.html'
    paginate_by = 5

    def post(self,request):
        form = AddFoodForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.person_of = request.user
            profile.save()
            return redirect('food:add_food')

    def get_queryset(self):  
        return Food.objects.filter(person_of=self.request.user)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AddFoodForm()
        return context


# for updating food given by the user
@login_required

def update_food(request, pk):
    food_items = Food.objects.filter(person_of=request.user)

    food_item = Food.objects.get(id=pk)
    form = AddFoodForm(instance=food_item)
    if request.method == 'POST':
        form = AddFoodForm(request.POST, instance=food_item)
        if form.is_valid():
            form.save()
            return redirect('calories:calprofile')
    myfilter = FoodFilter(request.GET, queryset=food_items)
    context = {'form': form, 'food_items': food_items, 'myfilter': myfilter}

    return render(request, 'add_food.html', context)


# for deleting food given by the user
@login_required

def delete_food(request, pk):
    food_item = Food.objects.get(id=pk)
    if request.method == "POST":
        food_item.delete()
        return redirect('calories:calprofile')
    context = {'food': food_item, }

    return render(request, 'delete_food.html', context) 


@login_required
def select_food(request):

    # for showing all food items available
    food_items = Food.objects.filter(person_of=request.user)
    form = SelectFoodForm(request.user)

    if request.method == 'POST':
        form = SelectFoodForm(request.user, request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.person_of = request.user
            instance.calorie_count = CalorieGoal.objects.get(person_of=request.user).calorie_goal
            instance.save()
            return redirect('/')
    else:
        form = SelectFoodForm(request.user)

    context = {'form': form, 'food_items': food_items}
    return render(request, 'select_food.html', context)

calorieapp/new_way/food/templates/add_food.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-lg-6">
    <div class="login">
        <div class="login-screen">
            <div class="app-title">
                <h1 class="headline">Add Food</h1>
            </div>
            <div>

            <form method="POST" action="" class="login-form form-inline">
              {% csrf_token %}
              
                {% for field in form %}
                <h5 class="form-labels">
                {{ field.label }}
                </h5>
                {{ field }}
                 
                {% endfor %}
           
                <input class="mt-2 btn" type="submit" value="Select">

            </form>
            </div>
           
        </div>
        
    </div>
    </div>
    <div class="col-lg-6 ">
    <div class="login">
        <div class="login-screen">
              <form method="get">
                  <h1 class="headline">{{ myFilter.form }}</h1>
<!--                  <button class="btn mt-2" type="submit"> Search </button>-->
              </form> 
        </div>
    </div>

        <h1 class="headline"> All Food Items </h1>
        <table class="table table-bordered text-center mt-3">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Food Name</th>
                    <th scope="col">Calories</th>
                    <th scope="col">Quantity</th>
                </tr>
            </thead>
            <tbody>
                {% for food in food_list %}
                <tr>
                    <td>{{ food.name }}</td>
                    <td>{{ food.calorie }}</td>
                    <td>{{ food.quantity }}</td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>  





        {% if is_paginated %}
        <div class="d-flex  flex-column ">
           <ul class="pagination d-flex flex-row justify-content-center">
               {% if page_obj.has_previous %}
               <li><a class="btn" style="width:60px;height:30px;" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
               {% else %}
               <li class="disabled btn" style="width:60px;height:30px;"><span>&laquo;</span></li>
               {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i %}
               <li class="active btn btn-info" style="width:60px;height:30px;"><span>{{ i }} <span class="sr-only">(curent)</span></span>
               </li>
               {% else %}
               <li><a class="btn" style="width:60px;height:30px;" href="?page={{ i }}">{{ i }}</a></li>
               {% endif %} {% endfor %} {% if page_obj.has_next %}
               <li><a class="btn" style="width:60px;height:30px;" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
               {% else %}
               <li class="disabled btn" style="width:60px;height:30px;"><span>&raquo;</span></li>
               {% endif %}
           </ul>
           <div class="d-flex flex-row justify-content-center">
               <span class="align-right">Showing {{ page_obj.start_index }}-{{ page_obj.end_index }} of {{ page_obj.paginator.count }}</span>
           </div>
        </div>
        {% endif %}




























    </div>
</div>
</div>

{% endblock content %}

calorieapp/new_way/food/templates/delete_food.html
{% extends 'base.html' %}

{% block content %}

<p class="text-center headline" style="font-size:32px">Are you sure you want to delete {{ food }}?</p>
<form method="POST" action="{% url 'food:delete_food' food.id %}" class="text-center">
	{% csrf_token %}
	<a href="{% url 'calories:calprofile' %}">Cancel</a>
	<input type="submit" name="Confirm">
</form>

{% endblock content %}

calorieapp/new_way/food/templates/select_food.html
{% extends 'base.html' %}

{% block content %}
    <div class="login mt-0">
        <div class="login-screen">
            <div class="app-title">
                <h1 class="headline">Select Food</h1>
            </div>

            <form method="POST" action="" class="login-form">
              {% csrf_token %}
              <h5 class="form-labels">
                  {{ form}}</h5>
                  <input class="btn login_btn pt-2" type="submit" value="Select">

            </form>
        </div>

    </div>
    <div class="container-fluid">
   <h1 class="headline text-center pb-3">All Food Items </h1>
        <table class="table table-bordered text-center">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Food Name</th>
                    <th scope="col">Calories</th>
                    <th scope="col">Quantity</th>
                </tr>
            </thead>
            <tbody>
                {% for food in food_items %}
                <tr>
                    <td>{{ food.name }}</td>
                    <td>{{ food.calorie }}</td>
                    <td>{{ food.quantity }}</td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>  
     </div>

{% endblock content %}