calorieapp/new_way/calorie_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calories.urls')),
    path('users/', include('users.urls')),
    path('food/', include('food.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
]

calorieapp/new_way/food/urls.py
from django.urls import path

from .views import  AddFood, FoodPerDay 
from .views import select_food,update_food,delete_food

app_name = 'food'

urlpatterns = [

    
    path('select_food/', select_food, name='select_food'),
	path('add_food/', AddFood.as_view(), name='add_food'),
	path('update_food/<str:pk>/', update_food, name='update_food'),
	path('delete_food/<str:pk>/', delete_food, name='delete_food'),
    path('profile/', FoodPerDay , name='profile'),
    

]

calorieapp/new_way/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [

    path('', views.userlist, name='userlist'),
    path('register', views.register, name='register'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('upload', views.upload_view, name='upload'),
    path('profile', views.profile_view, name='profile'),
    path('profile_update', views.profile_update, name='profile_update'),
    path("contact", views.contact, name="contact"),
    

]

calorieapp/new_way/users/models.py
from django.db import models
from django.templatetags.static import static
from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager


class AuthUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an e-mail address.')

        user = self.model(
            email=self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)

        return user


class AuthUser(AbstractUser):
    username = None
    email = models.EmailField(verbose_name='email', max_length=255, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = AuthUserManager()

    def __str__(self):
        return self.email

    def __repr__(self):
        return self.__str__()


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='profile_images/', null=True, default=None)

    @property
    def image(self):
        if self.avatar:
            return self.avatar.url

        return static('images/defaultUser.jpg')

calorieapp/new_way/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password, password_validators_help_text_html
from utils.upload import store_uploaded_file
from .models import Profile

AuthUser = get_user_model()


class LoginForm(forms.ModelForm):
    class Meta:
        model=AuthUser
        fields=['email','password']

    email = forms.EmailField(label='Email', max_length=50, widget=forms.EmailInput(attrs={"class":"form-control  mb-3",'placeholder': 'Email'}))
    password = forms.CharField(label='Password',widget= forms.PasswordInput(attrs={"class":"form-control mb-3",'placeholder': 'Password'}))
   

class RegisterForm(forms.ModelForm):
    class Meta:
        model = AuthUser
        fields = ['first_name', 'last_name', 'email']

    first_name = forms.CharField(
        max_length=255,
        required=True,
        label='First name',
        widget=forms.TextInput(attrs={'placeholder':'Enter your last name'})
    )

    last_name = forms.CharField(
        max_length=255,
        required=True,
        label='Last name',
        widget=forms.TextInput(attrs={'placeholder':'Enter your last name'})
    )

    password = forms.CharField(
        max_length=255,
        required=True,
        label='Password',
        widget=forms.PasswordInput,
    )

    password_confirmation = forms.CharField(
        max_length=255,
        required=True,
        label='Confirm password',
        widget=forms.PasswordInput,
    )

    def clean_password(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        password = self.cleaned_data.get('password')

        user = AuthUser(
            first_name=first_name,
            last_name=last_name,
       
        )

        validate_password(password, user=user)

        return password

    def clean_password_confirmation(self):
        password = self.cleaned_data.get('password')
        password_confirmation = self.cleaned_data.get('password_confirmation')

        if password_confirmation != password:
            raise forms.ValidationError('Password not confirmed.')

        return password_confirmation

    def save(self, commit=True):
        password = self.cleaned_data.get('password')
        self.instance.set_password(password)

        return super().save(commit)


class UserImageForm(forms.Form):
    image = forms.ImageField(label='Image to upload', required=True)

    def save(self):
        image = self.cleaned_data.get('image')
        store_uploaded_file(image)


class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']


class UserForm(forms.ModelForm):
    class Meta:
        model = AuthUser
        fields = ['first_name','last_name','email']


    
    first_name = forms.CharField(
        required=True,
        label='Prenume',
        widget=forms.TextInput
    )

    last_name = forms.CharField(
        required=True,
        label='Nume',
        widget=forms.TextInput
    )

    email = forms.EmailField(required=True,
                label='Email',
                widget=forms.TextInput())


    def save(self, *args, **kwargs):
        # u = self.instance.user
        # u.email = self.cleaned_data['email']
        # u.username = self.cleaned_data['username']
        self.instance.save()
        profile = super(UserForm, self).save(*args,**kwargs)
        return profile


#Contact us form

class ContactForm(forms.Form):
    first_name = forms.CharField(max_length = 50)
    last_name = forms.CharField(max_length = 50)
    email_address = forms.EmailField(max_length = 150)
    message = forms.CharField(widget = forms.Textarea, max_length = 2000)

calorieapp/new_way/users/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect, Http404, reverse
from users.forms import ContactForm, LoginForm, UserForm, RegisterForm, UserImageForm, ProfileImageForm
from django.contrib.auth import authenticate, login, logout
from users.email import email, send_register_mail
from django.contrib.auth.decorators import login_required
from django.contrib import messages



def userlist(request):
    return render(request, 'users/userlist.html')



# Create your views here.
def register(request):
    if request.method == 'GET':
        form = RegisterForm()
    else:
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()

            send_register_mail(user)

            return redirect('/')
      
    return render(request, 'users/register.html', {
        'form': form,
    })


def login_user(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'GET':
        form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)
        email = request.POST.get('email')
        password = request.POST.get('password')

        if not email or not password:
            raise Http404('Username or password not provided!')
        user = authenticate(request, email=email, password=password)

        if user is None:
            return render(request, 'users/login.html', {'msg':'Email or password is incorrect', 'form':form})
        else:
            login(request, user)

            return redirect('/')

    return render(request, 'users/login.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('/')


def upload_view(request):
    if request.method == 'GET':
        form = UserImageForm()
    else:
        form = UserImageForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()

            return render(request, 'users/file_uploaded.html')

    return render(request, 'users/upload.html', {
        'form': form
    })


@login_required(login_url="/users/login")
def profile_view(request):

    if request.method == 'GET':
        profile_form = UserForm(initial={
            'first_name':request.user.first_name,
            'last_name':request.user.last_name,
            'username':request.user.username,
            'email':request.user.email
        })
        form = ProfileImageForm()     
    else:
        form = ProfileImageForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect(reverse('users:profile'))

    return render(request, 'users/profile.html', {
        'form': form,
        'profile_form':profile_form
    })

def profile_update(request):
    profile_form = UserForm()
    if request.method == 'GET':
        form = ProfileImageForm()
    else:
        profile_update_form = UserForm(request.POST, instance=request.user)
        if profile_update_form.is_valid():
            profile_update_form.save()          
            return redirect(reverse('users:profile'))

    return render(request, 'users/profile.html', {
        'form': form,
        'profile_form':profile_form
    })


#Contact us

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Website Inquiry"
            body = {
                'first_name': form.cleaned_data['first_name'],
                'last_name': form.cleaned_data['last_name'],
                'email': form.cleaned_data['email_address'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, 'from@calorieapp.com', ['martinaslaura123@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect("calories:home")

    form = ContactForm()
    return render(request, "users/contact.html", {'form': form})

calorieapp/new_way/users/templates/users/contact.html
{% extends 'base.html' %}

{% block content %}
	<head>
	<style>
		h1 {text-align: center;}
		p {text-align: center;}
		div {text-align: center;}
	</style>
	</head>
	<div style="margin:80px">
		<h1 style = "color:#aae91b">About us </h1>
		<p style = "color:#fca921">
			CaloriePod gives you access to the biggest food database.
			Easily log everything you eat to your food diary for detailed insights about your nutrition. It’s a free nutrition tracker, calorie tracker, and macro tracker in one!
			CaloriePod isn’t just a meal tracker—or for counting calories.
			You’ll learn about your habits, get empowered to make smarter choices and find the motivation to get healthy, stay healthy, and conquer all your goals.
		</p>

		<h2 style = "color:#aae91b">Contact</h2>

		<h4 style = "color:#bbfc28">Contact us directly if you have any questions.</h4>

		<p style = "color:#fca921">
			Please write your name, email address and a message below if you have any questions.
			One of our staff members will be happy to contact you directly and answer your questions as soon as possible.
		</p>
		<form method="post">
        {% csrf_token %}
            {{form.as_p}}
            <button type="submit" style="color:#fca921">Submit</button>
        </form>
    </div>
{% endblock content %}

calorieapp/new_way/users/templates/users/file_uploaded.html
{% extends 'base.html' %}

{% block content %}
    File successfully uploaded!
{% endblock %}

calorieapp/new_way/users/templates/users/login.html
{% extends 'base.html' %}{% block title %}
<title>Login user</title>
{% endblock %} {% block content %}
<form class="login-form" action="{% url 'users:login' %}" method="POST">
    {% csrf_token %} 

        <label for="id_email">Email:</label>
          <input type="email" name="email" value="laura@laura.com" class="form-control  mb-3" placeholder="Email" maxlength="50" required="" id="id_email">

        <label for="id_password">Password:</label>
        
          <input type="password" name="password" class="form-control mb-3" placeholder="Password" required="" id="id_password">

    <input type="submit" value="Login">
</form>
<a href="{% url 'users:register' %}"><center>Don't have an account? Sign up!</center></a>
{% endblock %}

{% if msg %}  
    message: {{msg}}
{% endif %}

calorieapp/new_way/users/templates/users/profile.html
{% extends 'base.html' %}  {% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="row">
                <div class="col-12">
                    <img src="{{ request.user.profile.image }}" width="200" />
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="row">
                <form method="post" action="{% url 'users:profile_update' %}" enctype="multipart/form-data">
                    {% csrf_token %} {{ profile_form }}
                    <input type="submit" value="Modifica" />
                </form>
            </div>
            <div class="row">
                <div class="col-12">
                    Nume: {{ request.user.last_name }}
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    Prenume: {{ request.user.first_name }}
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    Email: {{ request.user.email }}
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    Username: {{ request.user.username }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

calorieapp/new_way/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="login">
        <div class="login-screen">
            <div class="app-title">
                <h1>Register</h1>
            </div>

            <form method="POST" action="{% url 'users:register' %}" class="login-form">
              {% csrf_token %} 
                 
      <label for="id_first_name">First name:</label>
       
        <input type="text" name="first_name" placeholder="First Name" maxlength="255" required="" id="id_first_name" class=" form-control">
    
      <label for="id_last_name">Last name:</label>
      
        <input type="text" name="last_name" placeholder="Last Name" maxlength="255" required="" id="id_last_name" class=" form-control">
        
      <label for="id_email">Email:</label>
      
        <input type="email" name="email" maxlength="255" required="" id="id_email" placeholder="E-mail" class=" form-control">

      <label for="id_password">Password:</label>

        <input type="password" name="password" maxlength="255" required="" id="id_password" placeholder="Enter Password" class=" form-control">

      <label for="id_password_confirmation">Confirm password:</label>
      
        <input type="password" name="password_confirmation" maxlength="255" required="" id="id_password_confirmation" placeholder="Confirm Password" class=" form-control">
        
                <input class="btn btn-primary btn-large btn-block" type="submit" name="Register">

            </form>

            <div class="d-flex justify-content-center links mt-8">
            Already have an account? <a href="{% url 'users:login' %}" class="ml-4">Login</a>
          </div>
        </div>{{form.errors}}
    </div>
    <script>

    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='First Name';
    form_fields[2].placeholder='Last Name';
    form_fields[3].placeholder='E-mail';
    form_fields[4].placeholder='Enter Password';


    for (var field in form_fields){ 
      form_fields[field].className += ' form-control'
    }
  </script>

{% endblock content %}

calorieapp/new_way/users/templates/users/upload.html
{% extends 'base.html' %}

{% block content %}
    <h1>Upload image</h1>
    <div class="container">
        <div>
            <form method="post" action="{% url 'users:upload' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Upload" />
            </form>
        </div>
    </div>
{% endblock %}

calorieapp/new_way/users/templates/users/userlist.html
{% extends 'base.html' %}{% block title %}
<title>Register user</title>
{% endblock %} {% block content %}
user list here
{% endblock %}