calorieapp/new_way/calorie_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calories.urls')),
    path('users/', include('users.urls')),
    path('food/', include('food.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
]

calorieapp/new_way/calories/urls.py
from django.urls import path

from .views import CalProfile, CalProfilePageView, calprofile

app_name = 'calories'

urlpatterns = [

    path('',CalProfilePageView, name='home'),
    path('calprofile', CalProfile.as_view() , name='calprofile'),

]

calorieapp/new_way/food/urls.py
from django.urls import path

from .views import  AddFood, FoodPerDay 
from .views import select_food,update_food,delete_food

app_name = 'food'

urlpatterns = [

    
    path('select_food/', select_food, name='select_food'),
	path('add_food/', AddFood.as_view(), name='add_food'),
	path('update_food/<str:pk>/', update_food, name='update_food'),
	path('delete_food/<str:pk>/', delete_food, name='delete_food'),
    path('profile/', FoodPerDay , name='profile'),
    

]

calorieapp/new_way/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [

    path('', views.userlist, name='userlist'),
    path('register', views.register, name='register'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('upload', views.upload_view, name='upload'),
    path('profile', views.profile_view, name='profile'),
    path('profile_update', views.profile_update, name='profile_update'),
    path("contact", views.contact, name="contact"),
    

]

calorieapp/new_way/calories/models.py
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL
from datetime import date
from food.models import Food


# Create your models here.

class CalorieGoal(models.Model):
    person_of = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    calorie_goal = models.PositiveIntegerField(default=0)



class FoodPerDay(models.Model):

    person_of = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    calorie_count = models.FloatField(default=0, null=True, blank=True)
    food_selected = models.ForeignKey(Food, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.FloatField(default=0)
    total_calorie = models.FloatField(default=0, null=True)
    date = models.DateField(auto_now_add=True)   
    food_today = models.ManyToManyField(Food, through='PostFood', related_name='inventory')


    def save(self, *args, **kwargs):  # new
           
        if self.food_selected != None:
            self.total_calorie = self.quantity * self.food_selected.calorie
            
            super(FoodPerDay, self).save(*args, **kwargs)
            

      
    def __str__(self):
        return str(self.person_of.username)

    def __str__(self):
        return self.food_selected

class PostFood(models.Model):

    profile = models.ForeignKey(FoodPerDay, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    calorie_amount = models.FloatField(default=0, null=True, blank=True)
    amount = models.FloatField(default=0)

calorieapp/new_way/calories/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ObjectDoesNotExist
from django import forms
from django.contrib.auth.models import User
from .models import CalorieGoal, Food, FoodPerDay


class CalProfileForm(forms.ModelForm):
    class Meta:
        model = FoodPerDay
        fields = ('food_selected', 'quantity',)

    def __init__(self, user, *args, **kwargs):
        super(CalProfileForm, self).__init__(*args, **kwargs)
        self.fields['food_selected'].queryset = Food.objects.filter(person_of=user)



class ProfileForm(forms.ModelForm):
    class Meta:
        model = CalorieGoal
        fields = ('calorie_goal',)

    def __init__(self, user, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        try:
           self.initial['calorie_goal'] = CalorieGoal.objects.get(person_of=user).calorie_goal
        except ObjectDoesNotExist:
            self.initial['calorie_goal'] = 0

calorieapp/new_way/calories/views.py
from django.views.generic import ListView
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from calories.forms import ProfileForm
from calories.models import FoodPerDay
from django.db.models import Sum

#  ContactForm
from .models import *
from datetime import timedelta
from django.utils import timezone
from datetime import date
from datetime import datetime


def calprofile(request):
    if request.method == 'GET':
        form = ProfileForm(request.user.id)

    elif request.method == "POST":
        form = ProfileForm(request.user.id, request.POST)

        if form.is_valid():
            CalorieGoal.objects.update_or_create(person_of_id=request.user.id,defaults={
                'calorie_goal': form.cleaned_data['calorie_goal']
            })


    return render(request, "calprofile.html", {'form':ProfileForm(request.user.id), 'food_items':Food.objects.filter(person_of_id=request.user.id)})

class CalProfile(ListView):
    model = FoodPerDay
    template_name = 'calprofile.html'


    def post(self,request):
        form = ProfileForm(request.user.id,request.POST)
        if form.is_valid():
            CalorieGoal.objects.update_or_create(person_of_id=request.user.id,defaults={
                'calorie_goal': form.cleaned_data['calorie_goal']
            })
        return redirect('calories:calprofile')

    def get_queryset(self):  
        return FoodPerDay.objects.filter(person_of=self.request.user).values('date').annotate(
            total=Sum('total_calorie')).values_list(
                'date','total','calorie_count')
      
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProfileForm(self.request.user.id)
        context['food_items'] = Food.objects.filter(person_of_id=self.request.user.id)
        return context



@login_required(login_url='users:login')

def HomePageView(request):
    return render(request, 'home.html')

@login_required(login_url='users:login')

def CalProfilePageView(request):
    # taking the latest profile object
    context = {
        'total_calorie': '',
        'calorie_goal': '',
        'calorie_goal_status': '',
        'over_calorie': '',
        'food_selected_today': '',
    }
    # default values
    try:    
        calories_goal = CalorieGoal.objects.get(person_of=request.user).calorie_goal
    except CalorieGoal.DoesNotExist:
        calories_goal = 0

    foods_today = FoodPerDay.objects.filter(person_of=request.user,date=datetime.now().date())
    food_today = 0
    for f in foods_today:
        food_today += f.total_calorie



    calorie_goal_status = calories_goal - food_today
    
    over_calorie = 0
    if calorie_goal_status < 0:
        over_calorie = abs(calorie_goal_status)
    
    context = {
    'total_calorie': int(food_today),
    'calorie_goal': calories_goal,
    'calorie_goal_status': calorie_goal_status,
    'over_calorie': over_calorie,
    'food_selected_today': foods_today,

    }
   

    return render(request, 'home.html', context)

calorieapp/new_way/calories/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Calorie App</title>
	<meta charset="utf-8">


	<link href="{% static 'css/base.css' %}" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


</head>
<body>
  <a href={% url "calories:home" %}><h1 class="logo text-center">Calorie Pod</h1></a>

<nav id="navbar-primary" class="navbar navbar-expand-lg navbar-default active" role="navigation">

    <!-- Brand and toggle get grouped for better mobile display -->

 <div class="container">
          <div class="navbar-header">
            <!-- Brand and toggle get grouped for better mobile display -->
          <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#resNav"  id='navbar-toggler'>
            <span class="navbar-toggler-icon" id="ham"></span>
          </button>
        </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="resNav">
            <ul class="navbar-nav justify-content-center">
              {% with url_name=request.resolver_match.url_name %}
              <li class="nav-item"><a class="nav-link  {% if url_name == 'home' %} active{% endif %}" href={% url "calories:home" %}>Home</a></li>
              <li class="nav-item"><a class="nav-link {% if url_name == 'calprofile' %} active{% endif %}" href={% url "calories:calprofile" %}>My Plan</a></li>
              <li class="nav-item"><a class="nav-link {% if url_name == 'add_food' %} active{% endif %}" href={% url "food:add_food" %}>Add Food</a></li>
              <li class="nav-item"><a class="nav-link {% if url_name == 'select_food' %} active{% endif %}" href={% url "food:select_food" %}>Select Food</a></li>
              <li class="nav-item"><a class="nav-link {% if url_name == 'contact' %} active{% endif %}" href={% url "users:contact" %}>Contact</a></li>

              {% endwith %}
            </ul>
            </div>
            <!-- /.navbar-collapse -->

 </div>
</nav>

<!-- header role="banner" -->
        {% block content %}
        {% endblock content %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

calorieapp/new_way/calories/templates/calprofile.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <h1 class="headline">My Plan :</h1>
        <div class="row mt-4 mb-4">
            <div class="col-lg-5 card card-body">
            <div class="app-title">
                
                <h1 class="text-center profile-text mt-2">Name: {{ request.user }} </h1>

            </div>

            <form method="POST" action="" class="login-form pt-4">
              {% csrf_token %}
                {% for field in form %}
                <h1>Calorie Goal For Today</h1>
                {{ field }}

                {% endfor %}
                <input class="btn login_btn profile-submit ml-3" type="submit" value="Select">

            </form>
        </div>
     
        <div class="col-lg-7">
        <h1 class="text-center headline pb-2">Records From Past Week</h1>
       
        <table class="table text-center">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Calorie Consumed</th>
                    <th scope="col">Calorie Goal</th>
                </tr>
            </thead>
            <tbody>
                {% for item in foodperday_list %}
                <tr>
                    <td>{{ item.0 }}</td>
                    <td>{{ item.1|floatformat:2 }}</td>
                    <td>{{ item.2|floatformat:2 }}</td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>  
    </div>
     
   
     </div>

    <h1 class="text-center headline">All Food Items</h1>

     <div class="row mt-5">
      <table class="table text-center">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Food Name</th>
                    <th scope="col">Calories</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for food in food_items %}
                <tr>
                    <td>{{ food.name }}</td>
                    <td>{{ food.calorie }}</td>
                    <td>{{ food.quantity }}</td>
                    <td><a class="btn btn-sm btn-info" href="{% url 'food:update_food' food.id %}">Update</a></td>
                    <td><a class="btn btn-sm " href="{% url 'food:delete_food' food.id %}">Delete</a></td>

                    
                </tr>
                {% endfor %}
            </tbody>
        </table>  
    </div>
</div>
{% endblock content %}

calorieapp/new_way/calories/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1 id="username" class="text-center mt-4 headline">Hi, {{ request.user}}!</h1>



<div class="container mt-2">
  <div class="row">
    <div class="col-lg-6 col-sm-12 item ">
      <div class="card item-card card-block">
        <h5 class="card-title mt-3 mb-3 text-center">Total Calories Consumed Today</h5>
        <p class="card-text text-center">{{ total_calorie }}</p> 
    </div>
    </div>
    <div class="col-lg-6 col-sm-12 item">
      <div class="card item-card card-block mt-sm-2 mt-lg-0">
        <h5 class="card-title  mt-3 mb-3 text-center">Calorie Goal For Today</h5>
        <p class="card-text text-center">{{ calorie_goal }}</p> 
  </div>
    </div>
  </div>
  
</div>
  
      <div class="card text-white text-center mt-4"  style="border-radius: 20px;">

        <div class="card-body">
          
          <p class="card-text text-center pt-3" style="font-size:22px"> 
          {% if calorie_goal_status > 0 %}
      You need  {{ calorie_goal_status }} calories more to reach your goal!
      {% elif calorie_goal == 0 %}
      <a href="{% url 'calories:calprofile' %}"> Enter your calorie goal for the day </a>
      {% else %}
      You surpassed your goal by {{ over_calorie|floatformat:2 }} calories!
      {% endif %} </p>

        </div>

      </div>

<h1 class="headline text-center mt-auto mb-auto">All Food Consumed Today </h1>
<div class="container table-responsive py-5"> 
<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr class="text-center">
      <th scope="col">Food</th>
      <th scope="col">Calorie</th>
      <th scope="col">Count</th>
    </tr>
  </thead>
  <tbody>
 
  
    {% for item in food_selected_today %}
    <tr class="text-center">
      <td> {{ item.food_selected.name }}</td>
      <td> {{ item.total_calorie|floatformat:2 }}</td>
      <td> {{ item.quantity }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>

<sub>
  <a href="{% url "users:logout" %}"><p align="right"><input type="button" style = "color:#fca921" value="Log Out"/></p></a>
</sub>
{% endblock content %}